export const allProjects = [
  {
    title: "QuantChain",
    slug: "quantchain",
    category: "Web",
    tags: "Fintech · Web3 · Crypto Exchange",
    excerpt: "Enterprise-grade cryptocurrency exchange with real-time order matching, multi-chain custody wallets, KYC/AML compliance, and a full fintech product suite.",
    image: "/images/QuantChain.png",
    link: "https://quantchain.vercel.app/",
    year: "2026",
    duration: "12 weeks",
    role: "Full-Stack Developer",
    overview:
      "QuantChain is an enterprise cryptocurrency exchange platform built for serious traders and institutions. It combines a real-time matching engine, multi-chain custody wallets, a full KYC/AML onboarding flow, staking products, P2P escrow trading, and a merchant payment gateway, all in a premium, mobile-first UI.",
    challenge:
      "A crypto exchange demands sub-second trade execution alongside institutional-grade security. The matching engine must handle high-throughput order flow without latency spikes, while the wallet system needs proper hot/cold segregation, HSM-ready signing, and watchtower monitoring across multiple chains.",
    solution:
      "Next.js 15 App Router for SSR and edge functions. Prisma + PostgreSQL as the authoritative trading ledger. Redis Streams for real-time pub/sub and order book delta broadcasts. WebSocket gateway delivering live market data to clients. A modular microservices architecture, Auth, Trading, Wallets, Settlement, Staking, P2P, Merchant, each independently deployable on Kubernetes.",
    results: [
      "Full-stack exchange live: real-time order book, multi-chain wallets, and KYC onboarding",
      "WebSocket-powered order book with sub-second update latency",
      "12 independent service domains enabling isolated scaling and zero-downtime deploys",
    ],
    techStack: [
      { name: "Next.js",    src: "/logos/nextjs-original.svg" },
      { name: "TypeScript", src: "/logos/typescript-original.svg" },
      { name: "React",      src: "/logos/reactnative-original.svg" },
      { name: "PostgreSQL", src: "/logos/postgresql-original.svg" },
      { name: "Node.js",    src: "/logos/nodejs-original.svg" },
      { name: "Tailwind",   src: "/logos/tailwindcss-original.svg" },
    ],
    features: [
      { num: "01", title: "Real-Time Order Book",  desc: "Live bid/ask depth with WebSocket-powered delta updates and sub-second latency for spot trading." },
      { num: "02", title: "Multi-Chain Wallets",   desc: "Custodial and non-custodial wallet support across major chains with hot/cold segregation and on-chain watchtowers." },
      { num: "03", title: "KYC / AML Engine",      desc: "Full onboarding flow with third-party KYC verification, AML risk scoring, and a compliance admin dashboard." },
      { num: "04", title: "Staking & P2P",         desc: "Flexible staking products with automated rewards, plus a P2P escrow trading desk with dispute resolution." },
      { num: "05", title: "Merchant Payments",     desc: "Crypto payment gateway with invoice generation, instant settlement, and a merchant analytics dashboard." },
    ],
  },
  {
    title: "Actora Labs",
    slug: "actora-labs",
    category: "Web",
    tags: "Web3 · React · Community",
    excerpt: "Coordination platform for Web3 communities, governance, task management, and on-chain contributor rewards.",
    image: "/images/actoraa.png",
    link: "https://actoralabs.com/",
    year: "2025",
    duration: "12 weeks",
    role: "Full-Stack Developer",
    overview:
      "Actora Labs is a coordination and governance platform for Web3 communities. It enables DAOs and community-run projects to manage tasks, vote on proposals, and automatically distribute rewards to contributors, all in one place.",
    challenge:
      "Web3 communities were coordinating via Discord threads and spreadsheets, fragile, opaque, and impossible to scale. They needed an on-chain-native platform that felt as polished as a Web2 SaaS product.",
    solution:
      "React frontend with wallet-based authentication via wagmi. Smart contract integration for on-chain voting and reward distribution. Supabase for off-chain task and community data with real-time subscriptions for live updates.",
    results: [
      "Used by 5 Web3 communities with 200+ combined members",
      "Reduced coordination overhead by an estimated 70%",
      "On-chain reward distribution with zero manual intervention",
    ],
    techStack: [
      { name: "React",      src: "/logos/reactnative-original.svg" },
      { name: "TypeScript", src: "/logos/typescript-original.svg" },
      { name: "Supabase",   src: "/logos/supabase-original.svg" },
      { name: "Node.js",    src: "/logos/nodejs-original.svg" },
    ],
    features: [
      { num: "01", title: "Task Management",     desc: "Assign, track, and verify community tasks with on-chain completion proofs." },
      { num: "02", title: "Governance Voting",   desc: "On-chain proposal voting with quorum rules and time-locked execution." },
      { num: "03", title: "Contributor Rewards", desc: "Automated token distribution based on verified task completion, no admin required." },
      { num: "04", title: "Community Dashboard", desc: "Real-time view of activity, open tasks, and a contributor leaderboard." },
    ],
  },
  {
    title: "4zee Properties",
    slug: "4zee-properties",
    category: "Web",
    tags: "Real Estate · Next.js · Africa",
    excerpt: "Pan-African luxury real estate platform covering property sales, investment, and construction across 10+ African markets.",
    image: "/images/4zee.png",
    link: "https://4zee-properties.vercel.app/",
    year: "2026",
    duration: "6 weeks",
    role: "Full-Stack Developer",
    overview:
      "4zee Properties is a pan-African luxury real estate platform connecting buyers, sellers, and investors across Nigeria, Kenya, and 10+ other markets. It covers premium residential, commercial, and off-plan properties, with agent profiles, investment tools, and an interactive Africa market map.",
    challenge:
      "Building a real estate platform that serves multiple African markets simultaneously meant handling diverse currencies, property types, and regional expectations, while still feeling like a globally competitive, premium product.",
    solution:
      "Next.js for performance and SEO-ready property listings. A rich data layer driving property cards, agent profiles, and per-market pages. Framer Motion for editorial-quality animations. Radix UI for accessible modals and filters. WhatsApp-integrated agent contact flow built for the African mobile-first market.",
    results: [
      "Pan-African coverage across Nigeria, Kenya, and 10+ regional markets",
      "Property discovery to agent WhatsApp contact in under 3 clicks",
      "Investment and construction verticals alongside core residential listings",
    ],
    techStack: [
      { name: "Next.js",    src: "/logos/nextjs-original.svg" },
      { name: "TypeScript", src: "/logos/typescript-original.svg" },
      { name: "React",      src: "/logos/reactnative-original.svg" },
      { name: "Tailwind",   src: "/logos/tailwindcss-original.svg" },
    ],
    features: [
      { num: "01", title: "Property Listings",    desc: "Filter by type, price, location, and status across luxury residential, commercial, and off-plan categories." },
      { num: "02", title: "Agent Profiles",       desc: "Verified agent pages with ratings, sold history, language support, and direct WhatsApp contact." },
      { num: "03", title: "Africa Market Map",    desc: "Interactive map surfacing active markets and investment opportunities across the continent." },
      { num: "04", title: "Investment Portal",    desc: "Dedicated section for off-plan investment opportunities with projected returns and project timelines." },
      { num: "05", title: "Construction Tracker", desc: "Live infrastructure and development projects with progress updates and smart-city showcases." },
    ],
  },
  {
    title: "Stonegate",
    slug: "stonegate",
    category: "Web",
    tags: "Fintech · React · Banking",
    excerpt: "Multi-currency online banking platform with international transfers, FX swaps, and virtual card management.",
    image: "/images/stonegate.png",
    link: "https://nexus-web-iota-ten.vercel.app",
    year: "2025",
    duration: "8 weeks",
    role: "Full-Stack Developer",
    overview:
      "Stonegate is a full-stack online banking platform with multi-currency accounts (GBP, USD, EUR), peer-to-peer transfers, real-time FX swaps, virtual and physical card management, and a full KYC onboarding flow. Built for a premium, modern banking experience from day one.",
    challenge:
      "Building a production-grade banking interface requires handling real financial data, multi-currency balances, and atomic transactions, all with a consumer-grade polish that builds user trust from the very first login.",
    solution:
      "React and TypeScript frontend with Supabase for auth, real-time data, and atomic RPC transaction functions to prevent double-spend. Multi-currency wallet system with live FX rate feeds. Zustand for client state, Framer Motion for transitions, and a fully responsive dark and light interface.",
    results: [
      "Full multi-currency banking product live with real auth, wallets, and transactions",
      "Atomic FX swap execution prevents double-spend across currency accounts",
      "Complete KYC onboarding flow from sign-up to verified account",
    ],
    techStack: [
      { name: "React",      src: "/logos/reactnative-original.svg" },
      { name: "TypeScript", src: "/logos/typescript-original.svg" },
      { name: "Supabase",   src: "/logos/supabase-original.svg" },
      { name: "Tailwind",   src: "/logos/tailwindcss-original.svg" },
      { name: "Node.js",    src: "/logos/nodejs-original.svg" },
    ],
    features: [
      { num: "01", title: "Multi-Currency Wallets",    desc: "GBP, USD, and EUR accounts each with dedicated IBANs and sort codes for local and international use." },
      { num: "02", title: "International Transfers",   desc: "Send to saved beneficiaries worldwide with real-time FX conversion at live rates." },
      { num: "03", title: "Currency Swap",             desc: "Atomic cross-currency swaps with live exchange rates, no spread surprises." },
      { num: "04", title: "Card Management",           desc: "Virtual and physical debit card controls per account, with freeze/unfreeze in one tap." },
      { num: "05", title: "Transaction History",       desc: "Full audit trail with status tracking, reference numbers, and per-transaction receipts." },
    ],
  },
  {
    title: "Ace Experience",
    slug: "ace-experience",
    category: "Web",
    tags: "F&B · Next.js · Tailwind",
    excerpt: "Premium culinary platform connecting professional chefs to high-end clientele.",
    image: "/images/ace.png",
    link: "https://ace-xperience.vercel.app/",
    year: "2025",
    duration: "4 weeks",
    role: "Frontend Developer",
    overview:
      "Ace Experience is a luxury culinary platform connecting private chefs with high-end clients for bespoke dining events, private dinners, and catering. The brand required a premium editorial aesthetic that matched the exclusivity of the service.",
    challenge:
      "The client needed a platform that felt like a Michelin-starred restaurant website, not a generic marketplace. It had to attract affluent clients and make chefs look world-class, while still converting visitors into booking inquiries.",
    solution:
      "Next.js for performance and SEO. Custom editorial design with full-bleed photography and refined typography. Framer Motion for smooth transitions. Chef profiles, menu showcases, and a multi-step inquiry booking flow.",
    results: [
      "30+ chef profiles onboarded at launch",
      "Booking inquiries up 40% vs. previous static site",
      "98 Lighthouse performance score on desktop",
    ],
    techStack: [
      { name: "Next.js",    src: "/logos/nextjs-original.svg" },
      { name: "TypeScript", src: "/logos/typescript-original.svg" },
      { name: "Tailwind",   src: "/logos/tailwindcss-original.svg" },
    ],
    features: [
      { num: "01", title: "Chef Profiles",  desc: "Rich profile pages with bio, cuisine specialty, gallery, and social links." },
      { num: "02", title: "Menu Showcase",  desc: "Beautiful menu presentation with dish photography and dietary filters." },
      { num: "03", title: "Booking Flow",   desc: "Multi-step inquiry form collecting event details, date, guest count, and preferences." },
      { num: "04", title: "SEO Optimized",  desc: "Structured data, og tags, and per-page meta for local and national search visibility." },
    ],
  },
  {
    title: "Indstr",
    slug: "indstr",
    category: "Web",
    tags: "DeFi · NFT · React",
    excerpt: "Decentralized finance and NFT marketplace with a sleek unified trading interface.",
    image: "/images/indstr.png",
    link: "#",
    year: "2025",
    duration: "7 weeks",
    role: "Frontend Developer",
    overview:
      "Indstr combines DeFi token trading with an NFT marketplace in a single, unified interface. Designed for experienced Web3 users who expect speed, clarity, and professional-grade tooling from a product.",
    challenge:
      "Most DeFi interfaces are cluttered and intimidating. Indstr needed to stand out with a clean aesthetic, powerful features behind a minimal UI, while handling real-time on-chain data reliably.",
    solution:
      "React with custom trading components. Web3 wallet integration via wagmi and viem. Real-time price feeds from on-chain oracles. An NFT display and bidding system built from scratch without heavy dependencies.",
    results: [
      "Interface praised for clarity in early user testing sessions",
      "Live trading and NFT listing features shipped on schedule",
      "Sub-200ms UI response time on all trading interactions",
    ],
    techStack: [
      { name: "React",      src: "/logos/reactnative-original.svg" },
      { name: "TypeScript", src: "/logos/typescript-original.svg" },
      { name: "Node.js",    src: "/logos/nodejs-original.svg" },
      { name: "Tailwind",   src: "/logos/tailwindcss-original.svg" },
    ],
    features: [
      { num: "01", title: "Token Trading",   desc: "Swap tokens with live price impact calculation, slippage control, and gas estimation." },
      { num: "02", title: "NFT Marketplace", desc: "List, discover, and bid on NFTs with rarity traits and full ownership history." },
      { num: "03", title: "Portfolio View",  desc: "Unified view of all token holdings and NFT assets across connected wallets." },
      { num: "04", title: "Analytics",       desc: "Historical price charts and trading volume per asset over custom time ranges." },
    ],
  },
  {
    title: "ChrisTech",
    slug: "christech",
    category: "Web",
    tags: "E-Commerce · Next.js · Nigeria",
    excerpt: "Nigeria's flagship electronics e-commerce platform, 500+ products, 7 categories, and nationwide delivery across all 36 states.",
    image: "/images/chris.png",
    link: "https://christech-nine.vercel.app/",
    year: "2026",
    duration: "6 weeks",
    role: "Full-Stack Developer",
    overview:
      "ChrisTech is Nigeria's premier electronics e-commerce platform. 500+ genuine flagship products across smartphones, laptops, audio, cameras, tablets, smartwatches, and gaming gear, delivered nationwide to all 36 states, with a 4.9-star average customer rating and 50K+ customers served.",
    challenge:
      "Building a consumer electronics store for the Nigerian market meant handling product discovery across 500+ SKUs, a reliable cart and checkout flow, and crafting a brand aesthetic that could compete with global tech retailers while feeling locally relevant.",
    solution:
      "Next.js for SEO-ready product and category pages with fast server rendering. Firebase for auth and data. Zustand for persistent client-side cart state. Framer Motion for premium editorial animations. A structured product data layer with category filtering, ratings, and search to keep large inventory navigable.",
    results: [
      "500+ products across 7 categories with filter, sort, and search",
      "Nationwide delivery coverage spanning all 36 Nigerian states",
      "50K+ customers with a 4.9 / 5.0 average rating at launch",
    ],
    techStack: [
      { name: "Next.js",    src: "/logos/nextjs-original.svg" },
      { name: "TypeScript", src: "/logos/typescript-original.svg" },
      { name: "Firebase",   src: "/logos/firebase-original.svg" },
      { name: "Tailwind",   src: "/logos/tailwindcss-original.svg" },
      { name: "React",      src: "/logos/reactnative-original.svg" },
    ],
    features: [
      { num: "01", title: "Product Catalog",      desc: "500+ SKUs across 7 categories with filter, sort, and search, smartphones, laptops, audio, cameras, tablets, gaming, and smartwatches." },
      { num: "02", title: "Cart & Checkout",       desc: "Persistent cart via Zustand and Firebase with a streamlined multi-step checkout flow and order confirmation." },
      { num: "03", title: "User Accounts",         desc: "Firebase authentication with an account dashboard for order history, saved items, and profile management." },
      { num: "04", title: "Category Pages",        desc: "Dedicated landing pages per product category with editorial photography and curated product grids." },
      { num: "05", title: "Nationwide Delivery",   desc: "Express 1-3 business day delivery coverage across all 36 Nigerian states with live tracking." },
    ],
  },
  {
    title: "PPAY",
    slug: "ppay-web",
    category: "Web",
    tags: "Fintech · Next.js · Payments",
    excerpt: "Marketing website for the PPAY fintech app, gift cards, airtime, live rates, virtual numbers, and offline payments across 10+ countries.",
    image: "/images/ppay-hero.png",
    link: "https://ppay-hva9.vercel.app/",
    year: "2026",
    duration: "4 weeks",
    role: "Frontend Developer",
    overview:
      "PPAY's marketing website showcases the full product, 9 core features including gift cards, airtime and data top-ups, live crypto and fiat rates, virtual numbers, instant transfers, virtual and physical cards, offline NearPay payments, savings, and a WhatsApp bot. Covering 10+ countries across Africa.",
    challenge:
      "A fintech landing page needs to communicate complex product capabilities clearly and fast. Users must understand the full value proposition within seconds, across any device and connection speed.",
    solution:
      "Next.js 16 with Tailwind CSS and Framer Motion. Each feature gets a dedicated scroll-triggered section with phone mockups and concise copy. Parallax scroll effects in the hero, a download-focused CTA architecture throughout, and optimized image handling for fast mobile loads.",
    results: [
      "All 9 product features presented with interactive scroll animations",
      "NearPay offline payment tech positioned as a world-first differentiator",
      "Conversion-optimized layout from hero to App Store and Play Store CTAs",
    ],
    techStack: [
      { name: "Next.js",    src: "/logos/nextjs-original.svg" },
      { name: "TypeScript", src: "/logos/typescript-original.svg" },
      { name: "React",      src: "/logos/reactnative-original.svg" },
      { name: "Tailwind",   src: "/logos/tailwindcss-original.svg" },
    ],
    features: [
      { num: "01", title: "Gift Cards",        desc: "Showcase of 500+ supported brands. Apple, Amazon, Netflix, Xbox, with instant delivery messaging." },
      { num: "02", title: "Airtime & Data",    desc: "MTN, Airtel, Glo, and 9mobile top-up feature section with 24/7 availability emphasis." },
      { num: "03", title: "NearPay",           desc: "Offline peer-to-peer payment technology highlighted as a proprietary world-first, zero internet required." },
      { num: "04", title: "Live Rates",        desc: "Real-time crypto and fiat exchange rate converter section with built-in buy/sell signals." },
      { num: "05", title: "Virtual Cards",     desc: "USD virtual card and premium physical Mastercard feature presentation with instant issuance copy." },
    ],
  },
  {
    title: "Koraq",
    slug: "koraq",
    category: "App",
    tags: "AI · Flutter · SME",
    excerpt: "AI-powered business assistant for SMEs, automates reporting, insights, and client communication.",
    image: "/images/koraq.png",
    link: "https://play.google.com/store/apps/details?id=com.koraq.app.koraq",
    year: "2026",
    duration: "10 weeks",
    role: "Mobile Developer",
    overview:
      "Koraq is an Android app that acts as an intelligent business assistant for small and medium enterprises. Available on Google Play, it automates routine reporting, surfaces key insights, and handles client follow-ups, giving owners hours back every week.",
    challenge:
      "SME owners wear too many hats. The challenge was building an AI assistant that felt genuinely useful, one that could ingest messy business data and return clean, actionable output without requiring any technical skill from the user.",
    solution:
      "Flutter with Dart for a high-performance Android experience. GPT-4 API handles natural language report generation and insights. Supabase stores business data. Push notifications drive automated reminders and follow-up prompts.",
    results: [
      "Saves business owners 5+ hours per week on average",
      "Live on Google Play with a polished native Android experience",
      "AI report generation under 4 seconds end-to-end",
    ],
    techStack: [
      { name: "Flutter",    src: "/logos/flutter-original.svg" },
      { name: "Dart",       src: "/logos/dart-original.svg" },
      { name: "TypeScript", src: "/logos/typescript-original.svg" },
      { name: "Supabase",   src: "/logos/supabase-original.svg" },
      { name: "Python",     src: "/logos/python-original.svg" },
      { name: "Node.js",    src: "/logos/nodejs-original.svg" },
    ],
    features: [
      { num: "01", title: "AI Report Generation", desc: "Ask Koraq for a weekly summary or monthly revenue breakdown, answered in plain English." },
      { num: "02", title: "Client Comms",          desc: "AI-drafted follow-up messages reviewed and sent by the business owner in one tap." },
      { num: "03", title: "Business Metrics",      desc: "Dashboard tracking revenue, expenses, client activity, and growth KPIs." },
      { num: "04", title: "Native Android",        desc: "Built with Flutter for a smooth, performant experience on Android devices." },
    ],
  },
  {
    title: "PPAY",
    slug: "ppay",
    category: "App",
    tags: "Payments · Flutter · Cross-Platform",
    excerpt: "Digital payments ecosystem for seamless peer-to-peer transfers and merchant payments.",
    image: "/images/ppay.png",
    link: "#",
    year: "2026",
    duration: "10 weeks",
    role: "Full-Stack Mobile Developer",
    overview:
      "PPAY is a digital payments app targeting peer-to-peer transfers and merchant point-of-sale use cases across Africa. The goal was a payments experience as smooth as Cash App, localized for the African market and optimized for low-bandwidth networks.",
    challenge:
      "Payments apps require handling regulatory compliance, edge-case failure modes, and network latency, all without breaking UX. Trust signals and perceived security were critical to user adoption.",
    solution:
      "Flutter with Dart for a polished, performant mobile build. Flutterwave for payment processing. An offline-capable transaction queue that syncs when connectivity returns. End-to-end transaction encryption.",
    results: [
      "P2P transfers complete in under 3 seconds on average",
      "Works on 2G/3G with offline transaction queuing",
      "Onboarding to first transaction in under 2 minutes",
    ],
    techStack: [
      { name: "Flutter",    src: "/logos/flutter-original.svg" },
      { name: "Dart",       src: "/logos/dart-original.svg" },
      { name: "Node.js",    src: "/logos/nodejs-original.svg" },
      { name: "PostgreSQL", src: "/logos/postgresql-original.svg" },
      { name: "TypeScript", src: "/logos/typescript-original.svg" },
    ],
    features: [
      { num: "01", title: "P2P Transfers",       desc: "Send money to contacts instantly using just a phone number or username." },
      { num: "02", title: "Merchant Payments",   desc: "QR-code based merchant payments with a built-in sales dashboard." },
      { num: "03", title: "Offline Queue",       desc: "Transactions queue locally and execute automatically when connectivity returns." },
      { num: "04", title: "Transaction History", desc: "Full history with receipts, status tracking, and one-tap dispute initiation." },
    ],
  },
  {
    title: "Velau",
    slug: "velau",
    category: "App",
    tags: "Trading · Automation · Flutter",
    excerpt: "Automated gold trading engine with algorithmic strategies and live portfolio dashboards.",
    image: "/images/velau.png",
    link: "#",
    year: "2026",
    duration: "9 weeks",
    role: "Mobile Developer",
    overview:
      "Velau is an automated trading app focused on gold commodities. Users set algorithmic strategies that execute automatically on market conditions, making active trading accessible to people without a trading background.",
    challenge:
      "Algorithmic trading requires precise execution and clear feedback. The app had to make complex strategy configuration feel simple, while the backend had to ingest market data and execute trades with low latency and no downtime.",
    solution:
      "Flutter frontend with Dart, featuring a visual strategy builder built around simple if-then logic. Python backend for market data ingestion and trade execution. Real-time portfolio PnL via WebSocket connections.",
    results: [
      "Strategy builder usable by non-technical traders within 10 minutes",
      "Average trade execution latency under 500ms",
      "Live portfolio PnL updates in real time via WebSocket",
    ],
    techStack: [
      { name: "Flutter",    src: "/logos/flutter-original.svg" },
      { name: "Dart",       src: "/logos/dart-original.svg" },
      { name: "Python",     src: "/logos/python-original.svg" },
      { name: "Node.js",    src: "/logos/nodejs-original.svg" },
      { name: "TypeScript", src: "/logos/typescript-original.svg" },
    ],
    features: [
      { num: "01", title: "Strategy Builder",    desc: "Visual if-then logic builder for creating custom automated trading rules without code." },
      { num: "02", title: "Live Execution",      desc: "Strategies execute automatically 24/7 without any manual intervention." },
      { num: "03", title: "Portfolio Dashboard", desc: "Real-time PnL, open positions, and historical performance with drawdown metrics." },
      { num: "04", title: "Risk Controls",       desc: "Stop-loss, take-profit, and daily drawdown limits configurable per strategy." },
    ],
  },
  {
    title: "Zapph",
    slug: "zapph",
    category: "App",
    tags: "Social · Flutter · Cross-Platform",
    excerpt: "Next-generation social communication app with HD video calls, voice messaging, real-time chat, location sharing, and AI-powered face detection.",
    image: "/images/zapph.jpg",
    link: "https://play.google.com/store/apps/details?id=com.zapph.zapph",
    year: "2026",
    duration: "12 weeks",
    role: "Mobile Developer",
    overview:
      "Zapph is a Flutter-native social communication platform that reimagines what a messaging app can be. It combines real-time messaging, HD video and voice calls via Agora RTC, voice notes, file sharing, QR-based friend discovery, location sharing, and ML-powered face detection, all in a single premium cross-platform experience on iOS and Android.",
    challenge:
      "Delivering a real-time communication app means solving multiple hard problems simultaneously: sub-200ms call connection via Agora RTC, reliable Firebase message delivery at scale, smooth in-app media capture and playback for voice notes and videos, and a polished UI that feels native on both platforms without splitting the codebase.",
    solution:
      "Flutter with Riverpod for clean, testable state management. Firebase for auth, Firestore real-time messaging, cloud storage, FCM push notifications, and analytics. Agora RTC Engine for low-latency HD video and voice calls. Google ML Kit for on-device face detection. flutter_sound for in-app voice recording and playback. go_router for clean navigation architecture.",
    results: [
      "HD video and voice calls with sub-200ms connection time via Agora RTC",
      "Real-time messaging with media, files, voice notes, and video across iOS and Android",
      "Live on Google Play with a polished cross-platform experience",
    ],
    techStack: [
      { name: "Flutter",  src: "/logos/flutter-original.svg" },
      { name: "Dart",     src: "/logos/dart-original.svg" },
      { name: "Firebase", src: "/logos/firebase-original.svg" },
      { name: "Node.js",  src: "/logos/nodejs-original.svg" },
    ],
    features: [
      { num: "01", title: "HD Video & Voice Calls", desc: "Low-latency group and 1:1 calls powered by Agora RTC Engine with noise cancellation and adaptive bitrate." },
      { num: "02", title: "Real-Time Messaging",    desc: "Instant messaging with read receipts, reactions, replies, and media previews via Firestore live subscriptions." },
      { num: "03", title: "Voice Notes",            desc: "In-app voice recording and waveform playback with flutter_sound, shareable as standalone media." },
      { num: "04", title: "Media & File Sharing",   desc: "Photos, videos, PDFs, and documents shared natively with in-app viewer and download support." },
      { num: "05", title: "QR & Contact Discovery", desc: "Add friends by scanning a unique QR code or importing from device contacts for fast onboarding." },
    ],
  },
];
